### ISSUE TITLE
Support bosh links for tsa information.

### ISSUE THREAD

**Issue by jasonkeene** [pivotal-cf-experimental/concourse-windows-release#2]
It would be preferable to use bosh links to discover the tsa's IP vs having this defined statically. You can also get the host_public_key using links.

**Comment by aminjam** [comment]
@jasonkeene Thanks! Ideally we would like to not have this release at all. If we can add the windows jobs to the upstream concourse release, we may not actually need this at all.

**Comment by sunjayBhatia** [comment]
Closing in favor of https://github.com/pivotal-cf-experimental/concourse-windows-worker-release/issues/7 since we lost the story for this issue
