### ISSUE TITLE
Bump concourse worker to 3.1.0

### ISSUE THREAD

**Issue by genevieve** [pivotal-cf-experimental/concourse-windows-release#4]

**Comment by sunjayBhatia** [comment]
@genevievelesperance Tracker story for this (since gitbot isn't configured): https://www.pivotaltracker.com/story/show/146417505

**Comment by sunjayBhatia** [comment]
@genevievelesperance Done. https://github.com/pivotal-cf-experimental/concourse-windows-release/releases/tag/3.1.1
