### ISSUE TITLE
add this to bosh.io

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf-experimental/concourse-windows-release#6]
It would be nice to be able to pull these directly from bosh.io. /cc: @cppforlife

**Comment by sunjayBhatia** [comment]
@jtarchie agreed! just put in a request

**Comment by crawsible** [comment]
@jtarchie We've done all we need to do (or can do) on this team, just waiting on @cppforlife. I'm going to accept the story, but I'm happy to keep the issue open until it gets resolved if you'd like.

**Comment by jtarchie** [comment]
It is there. http://bosh.io/releases/github.com/pivotal-cf-experimental/concourse-windows-worker-release?all=1

Accepted.
