### ISSUE TITLE
Concourse Windows Worker template should add the default port

### ISSUE THREAD

**Issue by snegivulcan** [pivotal-cf-experimental/concourse-windows-release#9]
> https://github.com/pivotal-cf-experimental/concourse-windows-worker-release/blob/master/jobs/concourse_windows/templates/concourse_windows.ps1.erb

Refer to the file above and the following code block in it

```
<%=
 tsa_addr = nil
  if_p("concourse_windows.tsa_host") do |host|
    tsa_addr = host
  end
  if tsa_addr.nil?
    tsa_addr = link("tsa").instances.first.address
  end
%>
```

If tsa_host is not provided, which is desirable in our case since we are using BOSH magic to automate the Concourse cluster operations for us and we do not want to specify IPs and let BOSH pick it up, the tsa_addr gets its value from `link("tsa").instances.first.address`

But `link("tsa").instances.first.address` just resolves to the IP and not the port. I propose that we look at the tsa_addr and add the default Concourse port (2222) if it is not of the form IP:port

I am not sure if it is an issue with BOSH that `link("tsa").instances.first.address` only resolves to the IP. Should it have included port as well ?

**Comment by snegivulcan** [comment]
I wanted to turn in a PR. But decided not to as i was not sure how to build and test the change :-)
Is there a link that describes the build steps and how to then use the newly built artifact to test with BOSH ?

**Comment by dpb587-pivotal** [comment]
+1, we also ran into this.
